### ISSUE TITLE
Needs some kind of way to unload/offload after it's done sampling

### ISSUE THREAD

**Issue by RandomGitUser321** [comfyanonymous/ComfyUI_bitsandbytes_NF4#4] opened 2024-08-11 16:16 UTC
As far as I know, a BNB'd model will anchor in the VRAM and can't easily be moved back to system memory. I have 8gb vram and even after sampling, it will stay mostly full and keep triggering the VAE decode to try to use tiled mode, due to not having enough VRAM.

It doesn't seem to free the vram, even after deleting the checkpointloadernf4 workflow and then doing something like making a new workflow using an sdxl model, for instance, the VRAM will still be full. If I'm not mistaken, I think you have to just delete the whole object that's anchored in the VRAM, but maybe keep a copy in system memory so that it can reload quick next time (ram->vram instead of from the drive)?

**Comment by Ratinod** [comment] 2024-08-11 16:24
And if you change the prompt text, the "out of memory" error will definitely appear.

**Comment by marhensa** [comment] 2024-08-11 18:40
> > And if you change the prompt text, the "out of memory" error will definitely appear.
> 
> Yeah, that's because it would normally try to offload the model to sysmem, then shuffle the t5 back into vram to generate the new prompt, then offload the t5 and reload the model, then sample. But since BnB is anchoring it, you'll probably OOM.

i have 12 GB of VRAM, the model (flux1-schnell-bnb-nf4.safetensors) is 11.2 GB, barely fits the VRAM (I'm making sure my system is very barebone and clean).

the first generation is working fast using VRAM, but the second prompt ComfyUI starts using lowvram mode, that loads unloads some models to RAM that makes it very slow.

is it any way to make it stays on VRAM?

or if the problem is T5 Clip? is there any way to fix this?

**Comment by comfyanonymous** [comment] 2024-08-11 19:52
This should be fixed with the latest commit.

**Comment by Ratinod** [comment] 2024-08-11 20:06
> This should be fixed with the latest commit.

I confirm. Now there is no OOM. Thanks.

**Comment by Ulexer** [comment] 2024-08-11 23:25
> This should be fixed with the latest commit.

Fix doesn't work for me. After first generation it executes text encoder on the cpu. 

```
got prompt
model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load FluxClipModel_
Loading 1 new model
C:\AI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
Requested to load Flux
Loading 1 new model
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
Requested to load AutoencodingEngine
Loading 1 new model
Prompt executed in 14.66 seconds
got prompt
loaded in lowvram mode 3991.193339538574
loaded completely 6049.751877021789 5859.856831550598
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
Requested to load AutoencodingEngine
Loading 1 new model
Prompt executed in 33.91 seconds
```

**Comment by marhensa** [comment] 2024-08-12 03:01
> > This should be fixed with the latest commit.
> 
> Fix doesn't work for me. After first generation it executes text encoder on the cpu.
> 
> ```
> got prompt
> model weight dtype torch.bfloat16, manual cast: None
> model_type FLUX
> Using xformers attention in VAE
> Using xformers attention in VAE
> Requested to load FluxClipModel_
> Loading 1 new model
> C:\AI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
>   out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
> Requested to load Flux
> Loading 1 new model
> 100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/it]
> Requested to load AutoencodingEngine
> Loading 1 new model
> Prompt executed in 14.66 seconds
> got prompt
> loaded in lowvram mode 3991.193339538574
> loaded completely 6049.751877021789 5859.856831550598
> 100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/it]
> Requested to load AutoencodingEngine
> Loading 1 new model
> Prompt executed in 33.91 seconds
> ```

As long as the prompt is not changed, the next seed generation will not bother the T5 Clip. That makes first generation always 2x faster than after prompt changed.

For me, and possibly for you as well, when the prompt is changed, the T5 Clip slows everything down and makes Comfy run in LOW VRAM mode. 

I don't know why, but that's what I've been observing.

**Comment by marhensa** [comment] 2024-08-12 03:08
![image](https://github.com/user-attachments/assets/4b052292-5c60-488a-832e-d5097f63fbe7)

is there any explanation for this, and how to prevent this?

I use the Schnell NF4, RTX 3060 12GB VRAM, on PC 32 GB RAM.

**Comment by marhensa** [comment] 2024-08-12 04:21
I found some workaround.

to prevent those slowdown after changing the prompt, 

click Unload Model from Comfy Manager

![image](https://github.com/user-attachments/assets/e0941ff5-b84a-42c5-92ac-5c1025382941)

1. change the prompt
2. click unload models
3. queue
4. profit! it's much faster this way!

 loading the models again is not that slow, it's faster than waiting for the Clip process / lowvram mode.

![image](https://github.com/user-attachments/assets/5265bf5b-cb8f-457c-9c87-3a68953a2845)

it's fast as it should be, 13-14 seconds per image, RTX 3060 12GB.

**Comment by comfyanonymous** [comment] 2024-08-12 04:52
Can I see your exact workflow?

**Comment by marhensa** [comment] 2024-08-12 05:54
> Can I see your exact workflow?

sure.. here, thank you @comfyanonymous for your help and attention.

[Workflow-NF4-Schnell.json](https://github.com/user-attachments/files/16577821/Workflow-NF4-Schnell.json)
![Workflow-NF4-Schnell](https://github.com/user-attachments/assets/0ef26418-e0b9-4ea0-86c8-d3a45e0cdd17)

this problem shown in video: https://youtu.be/2JaADaPbHOI
1. normal run without changing prompt (**quick**)
2. changing prompt (**slow** because turned into lowvram mode)
3. changing prompt with unload models (**quick** + 3 seconds)

**Comment by comfyanonymous** [comment] 2024-08-12 06:01
And both the node and comfyui are updated to the latest version?

**Comment by marhensa** [comment] 2024-08-12 06:09
> And both the node and comfyui are updated to the latest version?

![image](https://github.com/user-attachments/assets/e8cb7037-5ff2-4e90-a2be-976351c8903f)

ComfyUI: e9589d6d9246d1ce5a810be1507ead39fff50e04 (17 hours ago)
Said Node: f1935bd901860d4c1401dde5106f4c9543735ce8 ( 5 hours ago)

I see there's update in ComfyUI: [Support loading directly to vram with CLIPLoader node.](https://github.com/comfyanonymous/ComfyUI/commit/9acfe4df41b3b0ad8c600fc2d70a3af5c82cf4a4)

I'll check it, and give an update.

**Comment by boricuapab** [comment] 2024-08-12 06:12
I also notice a bit of a speed gain in the total prompt timing after clicking on the clear model button

![bbnf4modelclearing](https://github.com/user-attachments/assets/a87f8e30-4fac-4ca2-a372-e2d8e0a15874)

**Comment by marhensa** [comment] 2024-08-12 06:20
> > And both the node and comfyui are updated to the latest version?

> I see there's update in ComfyUI: [Support loading directly to vram with CLIPLoader node.](https://github.com/comfyanonymous/ComfyUI/commit/9acfe4df41b3b0ad8c600fc2d70a3af5c82cf4a4)
> 
> I'll check it, and give an update.

updated to the latest git pull both comfy and the node, still have this problem.

26 seconds: initial load first generate
16 seconds: 2nd generate without changing prompt
**47 seconds: 3rd generate _with_ changing prompt**
16 seconds: 4th generate without changing prompt
**20 seconds: 5th generate _with_ changing prompt + unload model first**

in video: https://youtu.be/nmjhOKDp6VY

**Comment by marhensa** [comment] 2024-08-12 10:38
> What Windows version and CPU are you guys using? This could be that annoying Windows 11 scheduler issue where it sometimes runs stuff on e-cores.

I'm using oldies Ryzen 5 3600, RTX 3060 12GB, RAM 32GB, 
OS: latest always updating Windows 11, currently 23H2 Build 22631.3958

Python 3.6.10, Comfy Manual (non portable), using virtualenv, torch 2.2.2+cu121.
Argument when running: `.\venv\Scripts\python.exe -s main.py --disable-xformers --listen --port 8189`

List of pip installed inside virtualenv: [pip list.txt](https://github.com/user-attachments/files/16580419/pip.list.txt)

Okay gotta go searching that scheduler issue. I can try to run it in Ubuntu WSL2 though, if all fails.

**Comment by Ulexer** [comment] 2024-08-12 12:27
> I found some workaround to prevent those slowdown **_after_** changing the prompt,
> 
> it's with click Unload Model from Comfy Manager.

Found a slightly more convenient workaround, to use modified node from https://github.com/LarryJane491/ComfyUI-ModelUnloader to automatically unload models after the image is generated.

![Снимок экрана 2024-08-12 150401](https://github.com/user-attachments/assets/3b0c3414-95d6-4d3c-b8f5-8a6647eb6221)

```
from comfy import model_management

class ModelUnloader:
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "image": ("IMAGE",),
            },
            "optional": {}
        }

    RETURN_TYPES = ("IMAGE",)
    RETURN_NAMES = ("image_output",)

    FUNCTION = "unload_model"

    CATEGORY = "loaders"

    def unload_model(self, image):
        loadedmodels=model_management.current_loaded_models
        unloaded_model = False
        for i in range(len(loadedmodels) -1, -1, -1):
            m = loadedmodels.pop(i)
            m.model_unload()
            del m
            unloaded_model = True
        if unloaded_model:
            model_management.soft_empty_cache()
        return (image,)

NODE_CLASS_MAPPINGS = {
    "Model unloader": ModelUnloader,
}
```

**Comment by marhensa** [comment] 2024-08-13 00:12
> > I found some workaround to prevent those slowdown **_after_** changing the prompt,
> > it's with click Unload Model from Comfy Manager.
> 
> Found a slightly more convenient workaround, to use modified node from https://github.com/LarryJane491/ComfyUI-ModelUnloader to automatically unload models after the image is generated.
> 

@Ulexer  the node wont connect to anything? how can I use it?

![image](https://github.com/user-attachments/assets/6d0cea5f-b91b-4dad-bec7-16c982f87355)

**Comment by MrUSBEN** [comment] 2024-08-13 03:15
> > I found some workaround to prevent those slowdown **_after_** changing the prompt,
> > it's with click Unload Model from Comfy Manager.
> 
> Found a slightly more convenient workaround, to use modified node from https://github.com/LarryJane491/ComfyUI-ModelUnloader to automatically unload models after the image is generated.
> 
> ![Снимок экрана 2024-08-12 150401](https://private-user-images.githubusercontent.com/50398767/357036549-3b0c3414-95d6-4d3c-b8f5-8a6647eb6221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTkyMzIsIm5iZiI6MTcyMzUxODkzMiwicGF0aCI6Ii81MDM5ODc2Ny8zNTcwMzY1NDktM2IwYzM0MTQtOTVkNi00ZDNjLWI4ZjUtOGE2NjQ3ZWI2MjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDAzMTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NTQ0ZjQ0NzAxYTI5ZmZjMTNmZWEyMzNhMDQyMTg1NzllNWY4ZjcwMjM5NDEzNDkxNmM0Y2FiZjAwZDgwZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1We3NjfwXnm88tirX2IeTu3z0x0tgHTxHTwL6O_xIFU)
> 
> ```
> from comfy import model_management
> 
> class ModelUnloader:
>     @classmethod
>     def INPUT_TYPES(cls):
>         return {
>             "required": {
>                 "image": ("IMAGE",),
>             },
>             "optional": {}
>         }
> 
>     RETURN_TYPES = ("IMAGE",)
>     RETURN_NAMES = ("image_output",)
> 
>     FUNCTION = "unload_model"
> 
>     CATEGORY = "loaders"
> 
>     def unload_model(self, image):
>         loadedmodels=model_management.current_loaded_models
>         unloaded_model = False
>         for i in range(len(loadedmodels) -1, -1, -1):
>             m = loadedmodels.pop(i)
>             m.model_unload()
>             del m
>             unloaded_model = True
>         if unloaded_model:
>             model_management.soft_empty_cache()
>         return (image,)
> 
> NODE_CLASS_MAPPINGS = {
>     "Model unloader": ModelUnloader,
> }
> ```

You node didn't work for me so i used the other unloader but the idea worked, so thankyou.

**Comment by comfyanonymous** [comment] 2024-08-13 07:22
If you still have issues with latest ComfyUI can you run it with: --verbose and give me the full log?

**Comment by marhensa** [comment] 2024-08-13 07:52
@comfyanonymous  Okay, I already update ComfyUI to the latest, and adds args `--verbose`

Here's the test:

- Initial generation: Prompt executed in 24.03 seconds
- 2nd, with prompt change: Prompt executed in 46.49 seconds _<-- still using lowvram_
- 3rd, **without** prompt change: Prompt executed in 15.84 seconds

With unloading method (from manager) and even with changing the prompt, the log is:
Unloading AutoencodingEngine
Unloading FluxClipModel_
Unloading Flux
got prompt
...
...
Prompt executed in 19.31 seconds _<-- no lowvram, even changing the prompt_

For me it's 46 vs 19 seconds, I'd choose to unload models even it's not convinent.

Here's the workflow: [Workflow-NF4-Schnell.json](https://github.com/user-attachments/files/16596160/Workflow-NF4-Schnell.json)
Here's the verbose logs: [verbose-logs-20240813-comfyui.txt](https://github.com/user-attachments/files/16596171/verbose-logs-20240813-comfyui.txt)

**Comment by comfyanonymous** [comment] 2024-08-13 08:05
Thanks it should actually be fixed now if you update ComfyUI.

**Comment by marhensa** [comment] 2024-08-13 08:22
> Thanks it should actually be fixed now if you update ComfyUI.

woaaw that was fast, you are genius, many thanks.

generating images with changing the prompt, now takes 21 seconds only:
_Prompt executed in 21.11 seconds_
I saw logs about unloading the models when the prompt changed.

even better than workaround above (unload node), 
without changing the prompt, there no need to unload, and the speed can be still fast:
_Prompt executed in 15.83 seconds_

thank you very much @comfyanonymous , you are the best!

**Closed** 2024-08-13 08:27 UTC
